name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Docker build
      run: docker build -t testproj:latest . && docker save testproj:latest | gzip > latestserver.tar.gz; dir
    
    - uses: actions/upload-artifact@v1
      with:
        name: server
        path: latestserver.tar.gz
